### ISSUE TITLE
Add `sqlglot-with-rs`?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/sqlglot-feedstock#390]
### Comment:

The big performance gains for `sqlglot` come from the optional `sqlglot[rs]` extra, which pulls a dependency on `sqlglotrs`, now a dependency of some [downstreams](https://github.com/conda-forge/dagster-libs-feedstock/pull/51).

https://github.com/tobymao/sqlglot/blob/v23.0.5/setup.py#L45

As they follow entirely separate versioning schemes, this should be another feedstock, but will take a bit of coordination here, as this repo should carry the (accurate) hard pin as `run_constrained`.

I'll fire up the `staged-recipes` request to get it started, and ping this team.

**Comment by thewchan** [comment]
@conda-forge/core what's the protocol here? I have added `sqlglot-rs` as a separate output here for this feedstock, would what @bollwyvl propose add to some confusion?

**Comment by bollwyvl** [comment]
Ok, i do see it now, not sure why my initial search came up empty.

What is perhaps missing is the hard pin on the specific version, which needs to be tested against what `Cargo.toml` says. Will take a look.

**Comment by thewchan** [comment]
@bollwyvl The actual rust components are in a different build and feedstock, located here: https://github.com/conda-forge/sqlglotrs-feedstock, `sqlglot-rs` depends on `sqlglotrs`, but does not build any rust component itself.

**Comment by bollwyvl** [comment]
yeah, i get that, but in the link to source above, it uses `==` to specify the version, but `pip check` won't validate that.

**Comment by thewchan** [comment]
Possibly we can add some checks here? https://github.com/conda-forge/sqlglot-feedstock/blob/4fa16d6f92a94e3387b93b5459ca9420fdad8f55/recipe/meta.yaml#L60
